name: dating_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+2
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  intl: ^0.17.0
  # FIREBASE Packages Section
  firebase_core: ^1.0.4
  checkbox_grouped: ^1.8.0
  nb_utils: ^4.4.10 # Firebase Core package required to use other firebase services
  firebase_auth: ^1.1.1
  chips_choice: ^2.0.1
  flutter_local_notifications: ^9.0.0
  wakelock: ^0.5.6
  audioplayers: ^0.20.1
  google_fonts: ^2.1.0
  flutter_vector_icons: ^1.0.0
  provider:
  cached_network_image: ^3.2.0
  http:
  # Used to Authenticate User Account (e.g. Sign in with Phone number, etc..)
  cloud_firestore: ^1.0.6     # Used to Save User Data in Database
  firebase_messaging: ^10.0.0   # Used to Send Push Notifications (e.g. New like, Visit and Message)
  firebase_storage:
  introduction_screen: ^2.1.0  # Used to Save User Profile Images on Cloud Storage
  agora_rtc_engine: ^4.0.7
  permission_handler:
  ntp: ^2.0.0
  localstorage: ^4.0.0+1
  shared_preferences:
  webview_flutter:
  http_auth:
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  fluttertoast:
  in_app_purchase: ^0.5.2 # This plugin help us to Sell VIP Subscription Plans in app
  geoflutterfire: ^3.0.0-nullsafety.2 # This plugin help us to query users by geolocation center
  flutter_svg: ^0.22.0 # This plugin help us to use custom svg icons
  flutter_launcher_icons: ^0.9.0 # Used to generate app icon launcher for both platforms android and iOS
  country_code_picker: ^2.0.1 # Used to Select User Country Code
  scoped_model: ^2.0.0-nullsafety.0 # Used to Manage Application State
  image_picker: ^0.7.4 # Used to select images from the User's device image library or take a new photo using the camera
  image_cropper: ^1.4.0 # Used to Crop/Rotate Selected images from user's device
  url_launcher: ^6.0.3 # Used to open link schemes in application or browser
  geolocator: ^7.7.0 # Used to get User location by GPS
  geocoding: ^2.0.0 # Used to translate User latitude and longitude coordinates into a readable address
  place_picker: ^0.9.19-nullsafety # This plugin help us to create Passport feature
  shimmer: ^2.0.0 # Used to create placeholder widget while app is loading the image
  timeago: ^3.0.2 # Used to create fuzzy timestamps: (e.g. "3 minutes ago")
  share: ^2.0.1 # Used to share application content in other applications
  flutter_cupertino_datetime_picker: ^2.0.1
  circular_check_box:




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/2.0x/
    - assets/3.0x/
    - assets/4.0x/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PangramSans
      fonts:
        - asset: assets/fonts/Pangram-Regular.ttf
        - asset: assets/fonts/Pangram-Black.otf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
